### ISSUE TITLE
Can't run the trtl.py - Syntax Error line 74

### ISSUE THREAD

**Issue by 4Reallive** [Sajo8/TRTL-CLI-py#1]
Followed the README instructions to install

Has a Syntax Error. Had a quick look although im still picking this up and am working on other projects.

Looking forward to working with you later. I'll start with an issue.

$ python trtl.py 
  File "trtl.py", line 74
    print(f"\nCurrent USD Price: ${mk_info['mk_usd']}")
                                                     ^
SyntaxError: invalid syntax

![image](https://user-images.githubusercontent.com/25818630/45684728-8ff6d780-bb8a-11e8-825d-ecd5262b6c46.png)

![image](https://user-images.githubusercontent.com/25818630/45684829-d0565580-bb8a-11e8-9bcf-4e4998d432bf.png)

**Comment by Sajo8** [comment]
Hey, 

Thanks a lot for the issue!

Which python version do you have? This program uses f'strings, which are only found in 3.6+ iirc, you may want to update to the latest version of python to run this

**Comment by 4Reallive** [comment]
Yes you are correct.
I am now on a fresh install on Ubuntu 18.04

Next problem is
python3.6 trtl.py 
Traceback (most recent call last):
  File "trtl.py", line 22, in <module>
    from checkpoints import checkpoints #for c or checkpoints
  File "/opt/TRTL-CLI-py/checkpoints.py", line 19, in <module>
    import dateutil.parser
ModuleNotFoundError: No module named 'dateutil'

**Comment by 4Reallive** [comment]
I will update you Readme.md
after this to assist any other people using the CLI.

**Comment by Sajo8** [comment]
Hmm 🤔 howcome? Try installing dateutil.parser?

**Comment by 4Reallive** [comment]
Successfully installed
pip install py-dateutil --user
pip install python-dateutil --user

Same message.

would you like me to raise a separate issue for this?

**Comment by Sajo8** [comment]
You can update the readme with the additional modules :D

**Comment by Sajo8** [comment]
is it working now?

**Comment by 4Reallive** [comment]
No it is not.
I have installed
pip install py-dateutil --user
pip install python-dateutil --user

Same message

Traceback (most recent call last):
File "trtl.py", line 22, in 
from checkpoints import checkpoints #for c or checkpoints
File "/opt/TRTL-CLI-py/checkpoints.py", line 19, in 
import dateutil.parser
ModuleNotFoundError: No module named 'dateutil'

**Comment by 4Reallive** [comment]
It is working now. I forgot to install using pip3
New to python3. and just getting back into dev.
Thanks for the support

**Comment by Sajo8** [comment]
no problem man
