### ISSUE TITLE
When going through ASCII art i crashed the program

### ISSUE THREAD

**Issue by 4Reallive** [Sajo8/TRTL-CLI-py#2]
> a
Traceback (most recent call last):
  File "trtl.py", line 166, in <module>
    print(askee(rand_number)['ascii']) #pass to function which handles it
  File "/opt/TRTL-CLI-py/askee.py", line 24, in askee
    f = open('ascii/' + filenames[fileornumber] + '.txt') #open corresponding file
FileNotFoundError: [Errno 2] No such file or directory: 'ascii/trtl.txt'

**Comment by 4Reallive** [comment]
Keep hitting a to replicate

**Comment by 4Reallive** [comment]
also happens when running ascii list

> ascii list
Traceback (most recent call last):
  File "trtl.py", line 170, in <module>
    ascii_art = askee(command_args[0]) # pass it to function
  File "/opt/TRTL-CLI-py/askee.py", line 31, in askee
    f = open(filenames['ascii/' + fileornumber + '.txt']) #open file of key with the same name with dir and file type appended to it
TypeError: list indices must be integers or slices, not str

**Comment by Sajo8** [comment]
reeeeeee

**Comment by Sajo8** [comment]
i replicated the 2nd issue

i cant replicate the 1st issue - i get a TypeError when trying to open trtl.txt (`a trtl`)

**Comment by 4Reallive** [comment]
Just keep hitting 'a' over and over,, sometimes its instant, sometimes it takes 20 shots.

**Comment by 4Reallive** [comment]
did you manage to replicate the first issue?

**Comment by Sajo8** [comment]
no i only get it with `a trtl`

**Comment by Sajo8** [comment]
[this](https://github.com/Sajo8/TRTL-CLI-py/commit/e9901be6d0ee0f4abe6542cdd1289b396ea00844) fixes it, thanks a lot! 👍

**Comment by 4Reallive** [comment]
@Sajo8 i found the problem and corrected it on my PC.

The problem is solved when i rename ascii\TRTL.txt  > ascii\trtl.txt

Are you running on Windows? Must be a Linux only thing. :-)

Suggest you change the case on that ascii text file
